// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuNJRKrkqhY-LVXZuqXsZmuJvJvd9OHac',
    appId: '1:673829408633:web:6079b519412f85654129a8',
    messagingSenderId: '673829408633',
    projectId: 'mediapp-5c445',
    authDomain: 'mediapp-5c445.firebaseapp.com',
    storageBucket: 'mediapp-5c445.firebasestorage.app',
    measurementId: 'G-7X5C4RW531',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuNJRKrkqhY-LVXZuqXsZmuJvJvd9OHac',
    appId: '1:673829408633:web:a719b02d725a67024129a8',
    messagingSenderId: '673829408633',
    projectId: 'mediapp-5c445',
    authDomain: 'mediapp-5c445.firebaseapp.com',
    storageBucket: 'mediapp-5c445.firebasestorage.app',
    measurementId: 'G-H3PQ831JH3',
  );
}
